---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: itsmetommy
  name: centos
spec:
  replicas: 1
  selector:
    matchLabels:
      component: centos
  template:
    metadata:
      labels:
        component: centos
    spec:
      containers:
      - name: centos
        image: centos:latest
        ports:
        - containerPort: 9988
---
apiVersion: v1
kind: Service
metadata:
  namespace: itsmetommy
  name: centos
  labels:
    app: centos
spec:
  ports:
  - port: 9988
  selector:
    app: centos