---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: itsmetommy
  name: persister-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: persister
  template:
    metadata:
      labels:
        component: persister
    spec:
      containers:
      - name: persister
        image: vincent36/ecg-persister:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: itsmetommy
  name: persister
  labels:
    app: persister
spec:
  ports:
  - port: 8080
    name: client
  selector:
    app: persister