---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: persister-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: persister
  template:
    metadata:
      labels:
        name: persister
        app: persister
    spec:
      containers:
      - name: persister
        image: vincent36/ecg-persister:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: persister
  labels:
    app: persister
spec:
  ports:
  - port: 8080
    name: persister-port
    targetPort: 8080
    protocol: TCP
  selector:
    app: persister