apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: itsmetommy
  name: postgres-demo
spec:
  serviceName: "postgres"
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        resources:
          requests:
            memory: "2000Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: postgres-config
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: itsmetommy
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: ecg
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: v1
kind: Service
metadata:
  namespace: itsmetommy
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: postgres