---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: vincent36/ecg-publisher:latest
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
  - port: 9090
    name: prometheus-port
    targetPort: 9090
    protocol: TCP
  selector:
    app: prometheus
  type: LoadBalancer