---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: publisher
  template:
    metadata:
      labels:
        component: publisher
    spec:
      containers:
      - name: publisher
        image: vincent36/ecg-publisher:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: publisher
  labels:
    app: publisher
spec:
  ports:
  - port: 8081
    name: client
    targetPort: 8081
    protocol: TCP
  selector:
    app: publisher
  type: LoadBalancer