---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: publisher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: publisher
  template:
    metadata:
      labels:
        name: publisher
        app: publisher
    spec:
      containers:
      - name: publisher
        image: vincent36/ecg-publisher:latest
        resources:
          requests:
            memory: "4000Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: publisher
  labels:
    app: publisher
spec:
  ports:
  - port: 8081
    name: publisher-port
    targetPort: 8081
    protocol: TCP
  selector:
    app: publisher
  type: LoadBalancer
  loadBalancerIP: 34.87.44.187