---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-socket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web-socket
  template:
    metadata:
      labels:
        name: web-socket
        app: web-socket
    spec:
      containers:
      - name: web-socket
        image: wincentrtz/skripsi-web-socket
        resources:
          requests:
            memory: "2000Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-socket
  labels:
    app: web-socket
spec:
  ports:
  - port: 3000
    name: web-socket-port
    targetPort: 3000
    protocol: TCP
  selector:
    app: web-socket
  # type: LoadBalancer